version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Sem volumes de código em produção 